<?php

declare(strict_types=1);

/**
 * Loads WordPress for the integration suite, through PHP's auto_prepend_file:
 *
 *     php -d auto_prepend_file=tests/WordPress/load.php vendor/bin/pest -c phpunit.wordpress.xml
 *
 * The suite runs against a plain WordPress, without the Pollora framework. The
 * fixture plugin is installed as a must-use plugin, loaded by the wp-cron.php
 * processes the tests start. This process skips it and the test file loads it
 * instead: Composer's autoloader must be loaded by Pest itself, otherwise Pest
 * prints nothing and exits with 0 whatever the results.
 */
$wordpressPath = getenv('WP_PATH') ?: dirname(__DIR__, 2).'/.wordpress';

if (! is_file($wordpressPath.'/wp-load.php')) {
    fwrite(STDERR, "WordPress not found in {$wordpressPath}: install it there with WP-CLI (see the wordpress job of .github/workflows/tests.yml) or set WP_PATH.\n");
    exit(1);
}

$muPlugins = $wordpressPath.'/wp-content/mu-plugins';

if (! is_dir($muPlugins)) {
    mkdir($muPlugins, 0777, true);
}

file_put_contents($muPlugins.'/pollora-hook-fixture.php', sprintf(
    "<?php\n\n// Generated by tests/WordPress/load.php.\nif (defined('POLLORA_HOOK_TEST_PROCESS')) {\n    return;\n}\n\nrequire_once %s;\nrequire_once %s;\n",
    var_export(dirname(__DIR__, 2).'/vendor/autoload.php', true),
    var_export(__DIR__.'/Fixtures/async-actions.php', true),
));

define('POLLORA_HOOK_TEST_PROCESS', true);
define('WP_USE_THEMES', false);
define('DISABLE_WP_CRON', true);

require $wordpressPath.'/wp-load.php';

unset($wordpressPath, $muPlugins);
